### ISSUE TITLE
Change README.md

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#19]
Delete the text in current README.md and add similar stuff as it was in https://github.com/CropAi/Backend till the PRE-REQUISITES

**Comment by abhushanaj** [comment]
Can i

**Comment by shreyakapoor08** [comment]
can i?

**Comment by tanishq9** [comment]
@abhu-A-J was a bit early ! So, assigning him !

**Comment by tanishq9** [comment]
@shreyakapoor08 You can also suggest some modifications in his PR and update accordingly if need be.
