### ISSUE TITLE
Suggest logo for android app [OPEN FOR ALL]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#24]
Add your valuable suggestions in the `demo-logos` folder. Preferred format : .svg amd .png

**Comment by abhushanaj** [comment]
Sir are we allowed to suggest the same ones we did in web application? Self created ones? Or do they need to be different?

**Comment by tanishq9** [comment]
The same logo will work everywhere.

**Comment by tanishq9** [comment]
They can be same as well.

**Comment by pranjalkalal** [comment]
https://drive.google.com/open?id=1-95BZ3JZjpf7caSV40lzLwfcaUWolQxV
