### ISSUE TITLE
Add imageView click listener [Make PR on 'DEV' Branch] [OPEN FOR ALL]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#29]
Instead of using button for uploading file, we will set a click listener on image view instead and use the button for selecting image file therefore we will change button text to ANALYZE. Also make sure the ANALYZE button when clicked shows a Toast of 'No file selected' if user has not uploaded any file and clicks on this button.

**Comment by abhishekgupta368** [comment]
Assign me

**Comment by tanishq9** [comment]
@abhishekgupta368 your origin/master is 14 commits behind upstream/master, please go through the updated code before writing 'Assign me'

**Comment by shwetagurnani** [comment]
Sir, I went through the updated codebase, please assign me this issue!

**Comment by abhishekgupta368** [comment]
I have read it,

**Comment by tanishq9** [comment]
@shwetagurnani was a bit early, assigning her. @abhishekgupta368 you can continue to work on your design PR.

**Comment by tanishq9** [comment]
Hey @shwetagurnani, what's the update on this issue, you have time till tomorrow 10am to close this.

**Comment by tanishq9** [comment]
I am making it open for all, so that everyone can try working on this issue.
