### ISSUE TITLE
Okhttp Network request [Make PR on 'DEV' Branch] [OPEN FOR ALL] 

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#30]
Send a POST request to https://crop-leaf.herokuapp.com/ with the image file selected by user as one of the parameter and log the response.

**Comment by darkmatter18** [comment]
Assign me please

**Comment by tanishq9** [comment]
You haven't forked the repo yet. Please go through the codebase once.

**Comment by darkmatter18** [comment]
@tanishq9 I didn't forked, but gone through the code base.

**Comment by tanishq9** [comment]
Ok, assigning you @darkmatter18

**Comment by darkmatter18** [comment]
@tanishq9 Thank you. I wanna discuss you one more thing that, as much as I know, `volly ` is better than `okhttp` and latest by Google. So can I use volly rather than okhttp. It would be better.

**Comment by tanishq9** [comment]
No, stick to Okhttp, it is much easier to work with.

**Comment by tanishq9** [comment]
@darkmatter18 you have time till tomorrow 10am to close this issue.

**Comment by tanishq9** [comment]
I am making it open for all, so that everyone can try working on this issue.

**Comment by tanishq9** [comment]
This issue will be worked upon after #37 is closed
