### ISSUE TITLE
Launch new activity when button is 'ANALYZE' button is clicked and imageView is not empty [MAKE PR ON 'DEV'][OPEN FOR ALL]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#38]
ImageView is assigned -> User clicks on 'ANALYZE' -> Launch new activity
ImageView is not assigned -> User clicks on 'ANALYZE' -> Show a Toast of 'No Image Selected'

**Comment by tanishq9** [comment]
This will be worked upon after #29 is closed.

**Comment by abhishekgupta368** [comment]
I will do it
