### ISSUE TITLE
Add a material button (already added material library dependency) in main activity xml file. 

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#4]
Keep the button name as 'Upload Image' and set it's id to : '/buttonUpload' (this is also the naming convention that we will follow for the whole project).

**Comment by abhishekgupta368** [comment]
can you assign me, please?

**Comment by ghost** [comment]
Can i work on this?

**Comment by shwetagurnani** [comment]
Can I work on it?

**Comment by tanishq9** [comment]
Assigning you @NtaoMoloi

**Comment by tanishq9** [comment]
@shwetagurnani  you can work on https://github.com/CropAi/Android-Application/issues/5

**Comment by tanishq9** [comment]
@NtaoMoloi have you started working on it ?
@shwetagurnani are you working on that issue ?

**Comment by ghost** [comment]
@tanishq9 yes i have.

**Comment by shwetagurnani** [comment]
@tanishq9  #5 is assigned to @satyam3976

**Comment by tanishq9** [comment]
You can work on that, I will assign you also.

**Comment by tanishq9** [comment]
@shwetagurnani  comment on that issue so that I can assign you.

**Comment by shwetagurnani** [comment]
@tanishq9 Sir,  I want to try #7 !

**Comment by tanishq9** [comment]
@NtaoMoloi you have 3 more hours to complete it !
