### ISSUE TITLE
Parse the JSON data received in ResultActivity [PR on 'DEV']

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#46]
Currently after fetching the getting the JSON response, the Result Activity looks like this(see the attached image), parse this JSON into Java objects and show the information in different views.

All the code change will be done in ResultActivity only. DON'T change code in any other activity.

![Screenshot (May 1, 2020 11_37_15 PM)](https://user-images.githubusercontent.com/35667308/80829958-ba819100-8c05-11ea-8ab7-bb77ccc1fd0b.png)

PS : Please do comment 'I am working on this' if you want to work on this issue, else PR won't be considered.

**Comment by shwetagurnani** [comment]
I am willing to work on this issue, please assign it to me.

**Comment by tanishq9** [comment]
ok, assigning you, you have to complete it before 6pm.

**Comment by shwetagurnani** [comment]
Thank you sir for assigning me this issue. I will be completing it on time.

**Comment by abhishekgupta368** [comment]
Can i Do this?

**Comment by tanishq9** [comment]
@abhishekgupta368 this one is not open for all !
