### ISSUE TITLE
Delete the textView in Main Activity's XML and add an imageView above the button.

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#5]
This imageView will be used to display the selected image file.

**Comment by abhishekgupta368** [comment]
can you assign me, please?

**Comment by Satyam3976** [comment]
Can I work on this issue? Please assign me @tanishq9

**Comment by tanishq9** [comment]
sure, assigning you @Satyam3976

**Comment by tanishq9** [comment]
@Satyam3976 any update ?

**Comment by tanishq9** [comment]
You can later take up this issue, so that I can assign it to someone else who is interested.

**Comment by shreyakapoor08** [comment]
can I try ?

**Comment by abhishekgupta368** [comment]
assign me
