### ISSUE TITLE
Add screenshots [OPEN FOR ALL]

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#54]
Create a markdown file by your name in the `screenshots` folder and add 3-4 screenshots of the app including 'on boarding', 'selecting image' and 'result'. Download the app using the APK given in README.md. Also, mention which device you tested the android app on in the PR description.

**Comment by abhushanaj** [comment]
Is this open for all Sir? Also, I am interested in it! Thank you

**Comment by tanishq9** [comment]
Yes, I have mentioned it now.

**Comment by CapTen101** [comment]
I ,too, want to contribute to the repository! :smile:

**Comment by CapTen101** [comment]
But I've found some issues in the app when I installed the application. Should I open the bugs as new issues @tanishq9 ?

**Comment by tanishq9** [comment]
@CapTen101 you can discuss these bugs with me on slack. We will open issues after that only.

**Comment by CapTen101** [comment]
Pardon but which Slack channel? There wasn't any mention in the contributing.md file.
PS. I haven't registered for gssoc20. Is that the reason? @tanishq9 
Also still can I contribute to the repository?

**Comment by CapTen101** [comment]
And the issue I encountered after installation of the app is that the app's functionality of analyzing the image is not working. Regardless of the Internet connection Toast always shows that "no Internet Connection".

**Comment by tanishq9** [comment]
All the contributors need to registered for GSSoC'20 to contribute. Anyways, if there is any bug, feel free to open an issue, I will look into it. Just make sure you describe the bug well enough !

**Comment by CapTen101** [comment]
ok, cool!

**Comment by rasacharjee** [comment]
I would like to contribute.
 What more screenshots needs to be attached?

**Comment by tanishq9** [comment]
Please read the issue description, everything is mentioned there.

**Comment by idk-231** [comment]
I would like to contribute. I am ready with the screenshots.

**Comment by tanishq9** [comment]
Make a PR. I will review it.

**Comment by idk-231** [comment]
# Device used 
- Motorola G5S Plus
Android- 8.1.0
## OnBoard Screen

![on Board](https://user-images.githubusercontent.com/20228645/81318168-7120be00-90ab-11ea-91d3-cf78d1f7094f.png)

## Analyze Screen

![Analyze screen](https://user-images.githubusercontent.com/20228645/81316684-84cb2500-90a9-11ea-862a-b20d2827bf24.png)

## Analyzing Screen

![analzingscreen](https://user-images.githubusercontent.com/20228645/81316599-65cc9300-90a9-11ea-8676-7641470a1876.png)

## Result Screen

![result](https://user-images.githubusercontent.com/20228645/81317287-4a15bc80-90aa-11ea-9f83-d0d4ac363e79.png)
