### ISSUE TITLE
Image Analyser not working [Android Q Bug]

### ISSUE THREAD

**Issue by CapTen101** [CropAi/Android-Application#56]
Device: Oneplus 6
OS: Android 10(Q) Oxygen OS

After installation, when I tried to test the app I noticed two problems:

- After selecting the image from the gallery, as soon as we return to the app there was an empty screen with no preview of any kind of the image. I'm not aware if it's not implemented or it's a bug. 

<img src="https://img.techpowerup.org/200503/empty-screen.jpg" alt="empty screen after upload" width="225" height="475"/>

- The second problem is that regardless of the Internet Connection, Toast message always shows "no Internet Connection".

<img src="https://img.techpowerup.org/200503/no-internet.jpg" alt="no internet problem" width="225" height="475"/>

**Comment by CapTen101** [comment]
Have a look at it @tanishq9

**Comment by tanishq9** [comment]
We have tested the application on Samsung, Google, Asus, Nokia and Redmi till now. Not sure whether this is a phone specific bug. There is no emulator present for OnePlus phones on AVD Manager or on GenyMotion, if you have a workaround for it then open a pull request.

**Comment by CapTen101** [comment]
Ok! Lemme see if I can correct it.

**Comment by CapTen101** [comment]
#### Ok so I did some research and found out this.

I've found that this problem will specifically be encountered in Android 10 (and further, probably Android R which is in developer beta) devices only. @tanishq9 The devices you've tested it on would not be having Android 10 and probably that's why the issue went unnoticed. 

After running the app, I saw this error:  "open failed: EACCES (Permission denied)"
That certainly means the app does not have the necessary permissions to select the particular image when the user selects it from the gallery.

The error is due to some major changes done after releasing Android 10(Q) and will persist in Android R too. Follow this:

- According to the Android documentation...
`Apps targeting Android 10 (API level 29) and higher are given scoped access into an external storage device, or scoped storage, by default. Such apps can see only their app-specific directory`

- Also in the documentation...
`In order to access any other file that another app has created, including files in a “downloads” directory, your app must use the Storage Access Framework, which allows the user to select a specific file.`

as mentioned in this article: [medium.com/EAccess](https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df)

**Comment by CapTen101** [comment]
Now, There are two workarounds for solving this problem:
- Adding an “opt-out” as a temporary attribute by setting the flag requestLegacyExternalStorage to false in our manifest.

- Else we can use openFileDescriptor. The idea is to make a copy of the file that the user picks in the media gallery and add it to our application cache directory and then resuming the usual process of analysing the image.

I can implement both but I feel that a more sturdy solution is option 2, openFileDescriptor.
Should I go with it? This is a major problem when we are trying to increase the reach of the application and an entire class of recently released android device users won't be able to use the app.

Do tell your thoughts on what you think about this... @tanishq9

**Comment by tanishq9** [comment]
Yes, this is a genuine issue for Android Q(API Level 29) , you can start working on it.

**Comment by CapTen101** [comment]
I'm on it! 😃 . Kindly assign me this issue.

**Comment by abhishekgupta368** [comment]
what is the error, can you explain please?

**Comment by tanishq9** [comment]
@CapTen101 any update on this issue ?

**Comment by CapTen101** [comment]
Hi, @tanishq9 Just woke up and the past two days have been pretty difficult for me. First I couldn't make it into GSoC just because of my project didn't get the required 'slot' from Google 😢. Otherwise, my mentor told me that I was pretty much selected. So yeah, I was in shock. I had to calm and compose myself. I'll give you the updates in a while 👍

**Comment by tanishq9** [comment]
Sure @CapTen101

**Comment by CapTen101** [comment]
Hi there @tanishq9. I wanted to clear one thing about the code written behind the app. I was working on the issue and I found this snippet of code: (cursor declaration)
![image](https://user-images.githubusercontent.com/45699327/81578369-552d5d00-93c8-11ea-9cf9-3ff3b064c322.png)

Can you explain a little bit more about that? What purpose is this code fulfilling like Is it obtaining the name of the image file?

**Comment by tanishq9** [comment]
I assume you must have used SQLite in some of your android application, you can draw an analogy using it, Cursor object gives you a pointer to iterate over all the given tabular data. And we aim to find the image path not the image name. This is the path we send to the backend as well, which then downloads this image and does further processing on it. I even shared a stackoverflow link for this image path issue.
Link to that issue : https://github.com/CropAi/Android-Application/issues/37

**Comment by CapTen101** [comment]
Yeah ok, so this is the absolute path of the image file?

**Comment by CapTen101** [comment]
But what confused me that if we only need the path of the image file then the getPath() method of the Uri class can be used for the same. Then why you have used Cursor for the same implementation. This is the doubt which intrigued me while going through the code actually @tanishq9

**Comment by CapTen101** [comment]
Also, should I make a PR in master or Dev? @tanishq9

**Comment by CapTen101** [comment]
I made the PR which fixes this bug. Kindly have a look @tanishq9

**Comment by tanishq9** [comment]
To set the imageView, we need the absolute path, the path which we get using Uri fails if the Uri is a content:// or any other non-file Uri, didn't you try that ? That is why I used Cursor implementation.

**Comment by CapTen101** [comment]
Ok, now I understand that. But the image view was working fine, though.
