### ISSUE TITLE
Request permission for selecting image file from user's device. Log the path of selected image.

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Android-Application#7]
When the upload file button is clicked check if this permission  `android.Manifest.permission.READ_EXTERNAL_STORAGE` is granted or not, if not then request this permission to be granted. 

If user grants the permission then make an implicit intent to pick image from gallery. Log the path of the image selected by user.

**Comment by abhishekgupta368** [comment]
can you assign me, please?

**Comment by shwetagurnani** [comment]
Can I work on it?

**Comment by tanishq9** [comment]
The permissions have to be requested when the button is clicked, so I would suggest you should make a button in XML, although that is a separate issue, which has been assigned to someone else. Assigning you @shwetagurnani

**Comment by tanishq9** [comment]
@shwetagurnani any update ? I see you haven't forked the repo yet. I am opening up this issue again to others, you can take up this issue later as well.
