### ISSUE TITLE
Please use releases/ to provide APK

### ISSUE THREAD

**Issue by IzzySoft** [CropAi/Android-Application#72]
Could you please use `releases/` and attach your APK there? This would also allow to see when there's a new version available – and enable you to provide release notes (if you wish). It's also where people usually look for, um, releases :wink: Thanks!

**Comment by IzzySoft** [comment]
Yeah, I hope I provided all details needed, dear bot :smile: If something is missing, just ask – I gladly update what I can.

**Comment by tanishq9** [comment]
@IzzySoft Are you referring to the debug APK ?

**Comment by IzzySoft** [comment]
No, to a signed APK for end-users to install. You currently seem to provide an APK via Google Drive, linked from your Readme. That should preferably be attached to a `release/` – first, as pointed out, to make it clear when there's an update, second to increase visibility (releases is what many users check first) – and third to have it available where Google is blocked (by censorship or user requirement).

I'd really love to try it, but I'm one of the "Google avoiders". As an added benefit to having the APK available here at `releases/`, I then could offer to provide it via [my repo](https://apt.izzysoft.de/fdroid), which is quite well-known meanwhile (serving about 500 apps incl. access via the F-Droid client, so users receive update notifications whenever there are new versions of apps they've installed).

**Comment by tanishq9** [comment]
Since, not all contributors are into Android development, that is why, I kept the APK download link in README.md. I will add the latest apk in the releases folder, not the signed one, as we don't intend to publish the app right now.

**Comment by tanishq9** [comment]
I have added the folder and APK inside it, incase of any further issue regarding this, you can reopen this issue. Closing this for now.

**Comment by IzzySoft** [comment]
Hi @tanishq9 – apologies for the delay… First thanks for providing the APK! I see I should have more specific: I meant using [releases](https://github.com/CropAi/Android-Application/releases) – didn't mean to bloat the repo with binaries, sorry! If you plan to update it from time to time, it's indeed better placed "outside", so contributors don't have to check out all the binary history (attaching to releases would not have that issue).

You write you do not (yet) plan to "publish" the app; does that just refer to "big places" like Google Play – or would you be OK if I'd place it into [my F-Droid repo](https://apt.izzysoft.de/fdroid)? Advantage of that would be to make it easier for your testers to stay up-to-date (provided you increase `versionCode` anytime you offer a new version). My repo is not that wide-spread as Google Play (not even all [F-Droid](https://f-droid.org/) users access it, though it can easily be added to the F-Droid client). Some other projects use it for their development versions as well. I gladly place it there if you permit!

PS: The `app-v1.apk` you've just uploaded is signed fine with v1+v2 signing; you just might wish to remove the `META-INF/*.version` files, e.g.

```
WARNING: META-INF/androidx.customview_customview.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.legacy_legacy-support-core-ui.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
```

(output from `apksigner`).

Looking forward to your permission to place the file into my repo. Meanwhile I hope to check the app myself soon – some of the plants in our little garden seem to need a little help, if only we knew which, so hopefully your app can tell us :smiley:
