### ISSUE TITLE
Results are far off

### ISSUE THREAD

**Issue by IzzySoft** [CropAi/Android-Application#75]
Today I finally found time to give your app a try. Took a photo of one of our roses which seems to have mildew. Fed it to CropAI. After about a minute, the app informed me my potato would be healthy.

Am I doing something wrong? Cannot have fed the wrong photo (we have no potatoes) – and treatment hints on potatoes are not especially helpful if I have issues with a rose :wink: Sent the photo again, same results. Sent a variant cropped to a single leaf, again the same results.

Here's the cropped photo (resized; the variant I sent for analysis was full-size): ![IMG_20200531_160304](https://user-images.githubusercontent.com/6781438/83354608-0edd7500-a35a-11ea-8816-5653be71171e.jpg)

Doesn't look like a potato leaf to me :rofl: Any hints?

PS: Looking at the screenshots embedded to the Readme, that's exactly what I get ("Potato Healthy"). If regardless on the image sent, it always displays that – what does the analysis do then, and what does it need a photo for?

Honestly, I'm not ranting. I know this is an "early bird" – I just want to understand what I can expect from it. I'll gladly try again later should that be a problem with the backend – or try with a later version of the Android app when available. Thanks!

**Comment by tanishq9** [comment]
It is obviously not possible to classify all such kind of crop leaf diseases as the dataset that we trained our model on consisted of only 15 classes. Also before raising issue you should have tried to figure out which dataset we have trained our model on and the API logic as well, for the ease of it we have also created an individual repository for each part of the project.

Also, the backend is designed in such a way that if it couldn't classify or the process takes more than 30 seconds then the output by default will be 'Potato Healthy'.

PS : The purpose of these repositories was to teach open source development to people and were a part of GSSoC'20 program, you can obviously clone/fork the repository and make your own modifications.

Happy Coding !

**Comment by IzzySoft** [comment]
Thanks for your reply, @tanishq9! Not being a dev but simply a user, I obviously approached it with completely wrong assumptions and expectations then, apologies. I've got no idea about your datasets, so I couldn't check that. And while I certainly could fork your repo, I'd fail at the coding. Sad, I was hoping for a FOSS app I could use with my little gardening. And (no accusation or finger-pointing), your Readme feeds that expectation: it states nothing about the nature of your project you explained to me now. It gives the impression to be what I expected:

> This is a crop advisory app for farmers and gardeners. It can diagnose pest damage, plant disease and nutrient deficiencies that are affecting crops and can offer corresponding treatment measures.

Nor do the "guidelines to use the application" say I should first check datasets etc :wink:

As for the "default potato": Maybe you could point that out in your Readme – or even better, give a hint in the app? It indeed took longer than 30s (after the countdown, it said "almost there" for a bit longer).

Thanks for taking the time to give me the background and explanations! Wish you all the best for the project. Hopefully, someone else then forks it to create an end-user version.
